In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


In [4]:
df = pd.read_csv('iris.csv').iloc[:,1:]
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
X = df.drop(columns= ['Species'])
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [8]:
y = df.Species.str.strip().eq('Iris-setosa').astype(int)
y

0      1
1      1
2      1
3      1
4      1
      ..
145    0
146    0
147    0
148    0
149    0
Name: Species, Length: 150, dtype: int64

In [9]:
y.unique()

array([1, 0])

In [18]:
x_train,x_test,y_train,y_test = train_test_split(
    X,y,test_size= 0.2,stratify = y, random_state =42
)

In [19]:
y_train.value_counts(normalize = True)

Species
0    0.666667
1    0.333333
Name: proportion, dtype: float64

In [20]:
y_test.value_counts(normalize = True)

Species
0    0.666667
1    0.333333
Name: proportion, dtype: float64

In [23]:
model = LogisticRegression().fit(x_train,y_train)

In [32]:
y_test_pred = model.predict(x_test)
y_train_pred = model.predict(x_train)

In [37]:
y_train_pred

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
from sklearn.metrics import accuracy_score, classification_report
print(f"test_accuracy: {accuracy_score(y_test,y_test_pred)}")
print(f"train_accuracy: {accuracy_score(y_train,y_train_pred)}")

print(f"test_classification_report: {classification_report(y_test,y_test_pred)}")
print(f"train_classification_report: {classification_report(y_train,y_train_pred)}")

test_accuracy: 1.0
train_accuracy: 1.0
test_classification_report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

train_classification_report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        80
           1       1.00      1.00      1.00        40

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120



In [38]:
x_train.values[0]

array([6. , 2.7, 5.1, 1.6])

In [43]:
import numpy as np 
model.predict(np.array([[6. , 2.7, 5.1, 1.6]]))

c:\Users\lokes\miniconda3\envs\fastapi\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [44]:
import joblib

joblib.dump(model, 'model.joblib')

['model.joblib']

In [45]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')